import type { Metadata } from "next";
import { Montserrat , Edu_NSW_ACT_Cursive} from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

const montserrat = Montserrat({
  variable: "--font-monteserrat",
  subsets: ["latin"],
});

const eduCursive = Edu_NSW_ACT_Cursive({
  variable: "--font-eduCursive",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${montserrat.className , eduCursive.variable}`}>
        <Theme>
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
